/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DeviceAccessManager {
  export type SuspicionEventStruct = {
    fingerprintHash: BytesLike;
    timestamp: BigNumberish;
    reason: string;
    scoreIncrease: BigNumberish;
    reportedBy: AddressLike;
  };

  export type SuspicionEventStructOutput = [
    fingerprintHash: string,
    timestamp: bigint,
    reason: string,
    scoreIncrease: bigint,
    reportedBy: string
  ] & {
    fingerprintHash: string;
    timestamp: bigint;
    reason: string;
    scoreIncrease: bigint;
    reportedBy: string;
  };

  export type DeviceRecordStruct = {
    fingerprintHash: BytesLike;
    owner: AddressLike;
    firstSeenAt: BigNumberish;
    lastAccessAt: BigNumberish;
    totalAccessCount: BigNumberish;
    suspicionScore: BigNumberish;
    isBlacklisted: boolean;
    isActive: boolean;
    encryptedMetadata: string;
    lastFingerprintChange: BigNumberish;
  };

  export type DeviceRecordStructOutput = [
    fingerprintHash: string,
    owner: string,
    firstSeenAt: bigint,
    lastAccessAt: bigint,
    totalAccessCount: bigint,
    suspicionScore: bigint,
    isBlacklisted: boolean,
    isActive: boolean,
    encryptedMetadata: string,
    lastFingerprintChange: bigint
  ] & {
    fingerprintHash: string;
    owner: string;
    firstSeenAt: bigint;
    lastAccessAt: bigint;
    totalAccessCount: bigint;
    suspicionScore: bigint;
    isBlacklisted: boolean;
    isActive: boolean;
    encryptedMetadata: string;
    lastFingerprintChange: bigint;
  };
}

export interface DeviceAccessManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACCESS_RATE_LIMIT"
      | "ADMIN_ROLE"
      | "BLACKLIST_THRESHOLD"
      | "DAILY_ACCESS_LIMIT"
      | "DEFAULT_ADMIN_ROLE"
      | "FINGERPRINT_CHANGE_COOLDOWN"
      | "MAX_DEVICES_PER_USER"
      | "MAX_SUSPICION_SCORE"
      | "ORACLE_ROLE"
      | "activeDevices"
      | "blacklistDevice"
      | "blacklistedDevices"
      | "deviceActivities"
      | "deviceActivityHistory"
      | "deviceDailyAccess"
      | "deviceLastAccess"
      | "deviceRecords"
      | "getDeviceActivityHistory"
      | "getDeviceAnalytics"
      | "getDeviceStats"
      | "getRoleAdmin"
      | "getSuspicionHistory"
      | "getUserDevices"
      | "globalBlacklist"
      | "grantRole"
      | "hasRole"
      | "pause"
      | "paused"
      | "recordAccess"
      | "registerDevice"
      | "removeDevice"
      | "renounceRole"
      | "reportSuspiciousActivity"
      | "revokeRole"
      | "supportsInterface"
      | "suspicionHistory"
      | "totalDevices"
      | "unpause"
      | "updateFingerprint"
      | "updateSuspicionScore"
      | "userDeviceMapping"
      | "userDevices"
      | "verifyDevice"
      | "whitelistDevice"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeviceAccessRecorded"
      | "DeviceBlacklisted"
      | "DeviceRegistered"
      | "DeviceRemoved"
      | "DeviceWhitelisted"
      | "FingerprintChanged"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SuspicionScoreUpdated"
      | "SuspiciousActivityDetected"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ACCESS_RATE_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BLACKLIST_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAILY_ACCESS_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FINGERPRINT_CHANGE_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DEVICES_PER_USER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUSPICION_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeDevices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistDevice",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistedDevices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deviceActivities",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deviceActivityHistory",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deviceDailyAccess",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deviceLastAccess",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deviceRecords",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeviceActivityHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeviceAnalytics",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeviceStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSuspicionHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDevices",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalBlacklist",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordAccess",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDevice",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDevice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportSuspiciousActivity",
    values: [BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspicionHistory",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDevices",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateFingerprint",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSuspicionScore",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userDeviceMapping",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userDevices",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDevice",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistDevice",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ACCESS_RATE_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BLACKLIST_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAILY_ACCESS_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FINGERPRINT_CHANGE_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DEVICES_PER_USER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SUSPICION_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeDevices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistedDevices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceActivities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceActivityHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceDailyAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceLastAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeviceActivityHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeviceAnalytics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeviceStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSuspicionHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDevices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportSuspiciousActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspicionHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDevices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateFingerprint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSuspicionScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDeviceMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDevices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistDevice",
    data: BytesLike
  ): Result;
}

export namespace DeviceAccessRecordedEvent {
  export type InputTuple = [
    fingerprintHash: BytesLike,
    user: AddressLike,
    contentId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    fingerprintHash: string,
    user: string,
    contentId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    fingerprintHash: string;
    user: string;
    contentId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceBlacklistedEvent {
  export type InputTuple = [
    fingerprintHash: BytesLike,
    reason: string,
    blacklistedBy: AddressLike
  ];
  export type OutputTuple = [
    fingerprintHash: string,
    reason: string,
    blacklistedBy: string
  ];
  export interface OutputObject {
    fingerprintHash: string;
    reason: string;
    blacklistedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceRegisteredEvent {
  export type InputTuple = [
    fingerprintHash: BytesLike,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    fingerprintHash: string,
    owner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    fingerprintHash: string;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceRemovedEvent {
  export type InputTuple = [fingerprintHash: BytesLike, owner: AddressLike];
  export type OutputTuple = [fingerprintHash: string, owner: string];
  export interface OutputObject {
    fingerprintHash: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceWhitelistedEvent {
  export type InputTuple = [
    fingerprintHash: BytesLike,
    whitelistedBy: AddressLike
  ];
  export type OutputTuple = [fingerprintHash: string, whitelistedBy: string];
  export interface OutputObject {
    fingerprintHash: string;
    whitelistedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FingerprintChangedEvent {
  export type InputTuple = [
    oldFingerprint: BytesLike,
    newFingerprint: BytesLike,
    user: AddressLike
  ];
  export type OutputTuple = [
    oldFingerprint: string,
    newFingerprint: string,
    user: string
  ];
  export interface OutputObject {
    oldFingerprint: string;
    newFingerprint: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SuspicionScoreUpdatedEvent {
  export type InputTuple = [
    fingerprintHash: BytesLike,
    oldScore: BigNumberish,
    newScore: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    fingerprintHash: string,
    oldScore: bigint,
    newScore: bigint,
    reason: string
  ];
  export interface OutputObject {
    fingerprintHash: string;
    oldScore: bigint;
    newScore: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SuspiciousActivityDetectedEvent {
  export type InputTuple = [
    fingerprintHash: BytesLike,
    user: AddressLike,
    activity: string,
    suspicionIncrease: BigNumberish
  ];
  export type OutputTuple = [
    fingerprintHash: string,
    user: string,
    activity: string,
    suspicionIncrease: bigint
  ];
  export interface OutputObject {
    fingerprintHash: string;
    user: string;
    activity: string;
    suspicionIncrease: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeviceAccessManager extends BaseContract {
  connect(runner?: ContractRunner | null): DeviceAccessManager;
  waitForDeployment(): Promise<this>;

  interface: DeviceAccessManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACCESS_RATE_LIMIT: TypedContractMethod<[], [bigint], "view">;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  BLACKLIST_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  DAILY_ACCESS_LIMIT: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FINGERPRINT_CHANGE_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  MAX_DEVICES_PER_USER: TypedContractMethod<[], [bigint], "view">;

  MAX_SUSPICION_SCORE: TypedContractMethod<[], [bigint], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  activeDevices: TypedContractMethod<[], [bigint], "view">;

  blacklistDevice: TypedContractMethod<
    [fingerprintHash: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  blacklistedDevices: TypedContractMethod<[], [bigint], "view">;

  deviceActivities: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string, string, bigint] & {
        fingerprintHash: string;
        timestamp: bigint;
        contentId: bigint;
        user: string;
        action: string;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  deviceActivityHistory: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  deviceDailyAccess: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  deviceLastAccess: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  deviceRecords: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint
      ] & {
        fingerprintHash: string;
        owner: string;
        firstSeenAt: bigint;
        lastAccessAt: bigint;
        totalAccessCount: bigint;
        suspicionScore: bigint;
        isBlacklisted: boolean;
        isActive: boolean;
        encryptedMetadata: string;
        lastFingerprintChange: bigint;
      }
    ],
    "view"
  >;

  getDeviceActivityHistory: TypedContractMethod<
    [fingerprintHash: BytesLike],
    [bigint[]],
    "view"
  >;

  getDeviceAnalytics: TypedContractMethod<
    [fingerprintHash: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        dailyAccesses: bigint;
        weeklyAccesses: bigint;
        monthlyAccesses: bigint;
        uniqueContent: bigint;
      }
    ],
    "view"
  >;

  getDeviceStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalDevices: bigint;
        _activeDevices: bigint;
        _blacklistedDevices: bigint;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSuspicionHistory: TypedContractMethod<
    [fingerprintHash: BytesLike],
    [DeviceAccessManager.SuspicionEventStructOutput[]],
    "view"
  >;

  getUserDevices: TypedContractMethod<
    [user: AddressLike],
    [DeviceAccessManager.DeviceRecordStructOutput[]],
    "view"
  >;

  globalBlacklist: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recordAccess: TypedContractMethod<
    [fingerprintHash: BytesLike, contentId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  registerDevice: TypedContractMethod<
    [fingerprintHash: BytesLike, encryptedMetadata: string],
    [boolean],
    "nonpayable"
  >;

  removeDevice: TypedContractMethod<
    [fingerprintHash: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  reportSuspiciousActivity: TypedContractMethod<
    [
      fingerprintHash: BytesLike,
      activity: string,
      suspicionIncrease: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  suspicionHistory: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, bigint, string, bigint, string] & {
        fingerprintHash: string;
        timestamp: bigint;
        reason: string;
        scoreIncrease: bigint;
        reportedBy: string;
      }
    ],
    "view"
  >;

  totalDevices: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateFingerprint: TypedContractMethod<
    [
      oldFingerprintHash: BytesLike,
      newFingerprintHash: BytesLike,
      encryptedMetadata: string
    ],
    [void],
    "nonpayable"
  >;

  updateSuspicionScore: TypedContractMethod<
    [fingerprintHash: BytesLike, newScore: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  userDeviceMapping: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  userDevices: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  verifyDevice: TypedContractMethod<
    [fingerprintHash: BytesLike, claimedOwner: AddressLike],
    [[boolean, bigint] & { isValid: boolean; suspicionScore: bigint }],
    "view"
  >;

  whitelistDevice: TypedContractMethod<
    [fingerprintHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACCESS_RATE_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BLACKLIST_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAILY_ACCESS_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FINGERPRINT_CHANGE_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DEVICES_PER_USER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUSPICION_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeDevices"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "blacklistDevice"
  ): TypedContractMethod<
    [fingerprintHash: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blacklistedDevices"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deviceActivities"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string, string, bigint] & {
        fingerprintHash: string;
        timestamp: bigint;
        contentId: bigint;
        user: string;
        action: string;
        blockNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deviceActivityHistory"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deviceDailyAccess"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deviceLastAccess"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deviceRecords"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint
      ] & {
        fingerprintHash: string;
        owner: string;
        firstSeenAt: bigint;
        lastAccessAt: bigint;
        totalAccessCount: bigint;
        suspicionScore: bigint;
        isBlacklisted: boolean;
        isActive: boolean;
        encryptedMetadata: string;
        lastFingerprintChange: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeviceActivityHistory"
  ): TypedContractMethod<[fingerprintHash: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDeviceAnalytics"
  ): TypedContractMethod<
    [fingerprintHash: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        dailyAccesses: bigint;
        weeklyAccesses: bigint;
        monthlyAccesses: bigint;
        uniqueContent: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeviceStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalDevices: bigint;
        _activeDevices: bigint;
        _blacklistedDevices: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSuspicionHistory"
  ): TypedContractMethod<
    [fingerprintHash: BytesLike],
    [DeviceAccessManager.SuspicionEventStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDevices"
  ): TypedContractMethod<
    [user: AddressLike],
    [DeviceAccessManager.DeviceRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalBlacklist"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordAccess"
  ): TypedContractMethod<
    [fingerprintHash: BytesLike, contentId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerDevice"
  ): TypedContractMethod<
    [fingerprintHash: BytesLike, encryptedMetadata: string],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeDevice"
  ): TypedContractMethod<[fingerprintHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reportSuspiciousActivity"
  ): TypedContractMethod<
    [
      fingerprintHash: BytesLike,
      activity: string,
      suspicionIncrease: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "suspicionHistory"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, bigint, string, bigint, string] & {
        fingerprintHash: string;
        timestamp: bigint;
        reason: string;
        scoreIncrease: bigint;
        reportedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalDevices"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFingerprint"
  ): TypedContractMethod<
    [
      oldFingerprintHash: BytesLike,
      newFingerprintHash: BytesLike,
      encryptedMetadata: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSuspicionScore"
  ): TypedContractMethod<
    [fingerprintHash: BytesLike, newScore: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userDeviceMapping"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "userDevices"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyDevice"
  ): TypedContractMethod<
    [fingerprintHash: BytesLike, claimedOwner: AddressLike],
    [[boolean, bigint] & { isValid: boolean; suspicionScore: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "whitelistDevice"
  ): TypedContractMethod<[fingerprintHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "DeviceAccessRecorded"
  ): TypedContractEvent<
    DeviceAccessRecordedEvent.InputTuple,
    DeviceAccessRecordedEvent.OutputTuple,
    DeviceAccessRecordedEvent.OutputObject
  >;
  getEvent(
    key: "DeviceBlacklisted"
  ): TypedContractEvent<
    DeviceBlacklistedEvent.InputTuple,
    DeviceBlacklistedEvent.OutputTuple,
    DeviceBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "DeviceRegistered"
  ): TypedContractEvent<
    DeviceRegisteredEvent.InputTuple,
    DeviceRegisteredEvent.OutputTuple,
    DeviceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DeviceRemoved"
  ): TypedContractEvent<
    DeviceRemovedEvent.InputTuple,
    DeviceRemovedEvent.OutputTuple,
    DeviceRemovedEvent.OutputObject
  >;
  getEvent(
    key: "DeviceWhitelisted"
  ): TypedContractEvent<
    DeviceWhitelistedEvent.InputTuple,
    DeviceWhitelistedEvent.OutputTuple,
    DeviceWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "FingerprintChanged"
  ): TypedContractEvent<
    FingerprintChangedEvent.InputTuple,
    FingerprintChangedEvent.OutputTuple,
    FingerprintChangedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SuspicionScoreUpdated"
  ): TypedContractEvent<
    SuspicionScoreUpdatedEvent.InputTuple,
    SuspicionScoreUpdatedEvent.OutputTuple,
    SuspicionScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SuspiciousActivityDetected"
  ): TypedContractEvent<
    SuspiciousActivityDetectedEvent.InputTuple,
    SuspiciousActivityDetectedEvent.OutputTuple,
    SuspiciousActivityDetectedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DeviceAccessRecorded(bytes32,address,uint256,uint256)": TypedContractEvent<
      DeviceAccessRecordedEvent.InputTuple,
      DeviceAccessRecordedEvent.OutputTuple,
      DeviceAccessRecordedEvent.OutputObject
    >;
    DeviceAccessRecorded: TypedContractEvent<
      DeviceAccessRecordedEvent.InputTuple,
      DeviceAccessRecordedEvent.OutputTuple,
      DeviceAccessRecordedEvent.OutputObject
    >;

    "DeviceBlacklisted(bytes32,string,address)": TypedContractEvent<
      DeviceBlacklistedEvent.InputTuple,
      DeviceBlacklistedEvent.OutputTuple,
      DeviceBlacklistedEvent.OutputObject
    >;
    DeviceBlacklisted: TypedContractEvent<
      DeviceBlacklistedEvent.InputTuple,
      DeviceBlacklistedEvent.OutputTuple,
      DeviceBlacklistedEvent.OutputObject
    >;

    "DeviceRegistered(bytes32,address,uint256)": TypedContractEvent<
      DeviceRegisteredEvent.InputTuple,
      DeviceRegisteredEvent.OutputTuple,
      DeviceRegisteredEvent.OutputObject
    >;
    DeviceRegistered: TypedContractEvent<
      DeviceRegisteredEvent.InputTuple,
      DeviceRegisteredEvent.OutputTuple,
      DeviceRegisteredEvent.OutputObject
    >;

    "DeviceRemoved(bytes32,address)": TypedContractEvent<
      DeviceRemovedEvent.InputTuple,
      DeviceRemovedEvent.OutputTuple,
      DeviceRemovedEvent.OutputObject
    >;
    DeviceRemoved: TypedContractEvent<
      DeviceRemovedEvent.InputTuple,
      DeviceRemovedEvent.OutputTuple,
      DeviceRemovedEvent.OutputObject
    >;

    "DeviceWhitelisted(bytes32,address)": TypedContractEvent<
      DeviceWhitelistedEvent.InputTuple,
      DeviceWhitelistedEvent.OutputTuple,
      DeviceWhitelistedEvent.OutputObject
    >;
    DeviceWhitelisted: TypedContractEvent<
      DeviceWhitelistedEvent.InputTuple,
      DeviceWhitelistedEvent.OutputTuple,
      DeviceWhitelistedEvent.OutputObject
    >;

    "FingerprintChanged(bytes32,bytes32,address)": TypedContractEvent<
      FingerprintChangedEvent.InputTuple,
      FingerprintChangedEvent.OutputTuple,
      FingerprintChangedEvent.OutputObject
    >;
    FingerprintChanged: TypedContractEvent<
      FingerprintChangedEvent.InputTuple,
      FingerprintChangedEvent.OutputTuple,
      FingerprintChangedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SuspicionScoreUpdated(bytes32,uint256,uint256,string)": TypedContractEvent<
      SuspicionScoreUpdatedEvent.InputTuple,
      SuspicionScoreUpdatedEvent.OutputTuple,
      SuspicionScoreUpdatedEvent.OutputObject
    >;
    SuspicionScoreUpdated: TypedContractEvent<
      SuspicionScoreUpdatedEvent.InputTuple,
      SuspicionScoreUpdatedEvent.OutputTuple,
      SuspicionScoreUpdatedEvent.OutputObject
    >;

    "SuspiciousActivityDetected(bytes32,address,string,uint256)": TypedContractEvent<
      SuspiciousActivityDetectedEvent.InputTuple,
      SuspiciousActivityDetectedEvent.OutputTuple,
      SuspiciousActivityDetectedEvent.OutputObject
    >;
    SuspiciousActivityDetected: TypedContractEvent<
      SuspiciousActivityDetectedEvent.InputTuple,
      SuspiciousActivityDetectedEvent.OutputTuple,
      SuspiciousActivityDetectedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
