/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { DeviceAccessManager } from "./DeviceAccessManager";
export type { PaywallCore } from "./PaywallCore";
export type { PaywallRegistry } from "./PaywallRegistry";
export type { PaywallSubscriptions } from "./PaywallSubscriptions";
