/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PaywallSubscriptions {
  export type SubscriptionPlanStruct = {
    planId: BigNumberish;
    creator: AddressLike;
    name: string;
    description: string;
    monthlyPriceUSDC: BigNumberish;
    annualPriceUSDC: BigNumberish;
    maxDevices: BigNumberish;
    includedContentIds: BigNumberish[];
    isActive: boolean;
    subscriberCount: BigNumberish;
    createdAt: BigNumberish;
  };

  export type SubscriptionPlanStructOutput = [
    planId: bigint,
    creator: string,
    name: string,
    description: string,
    monthlyPriceUSDC: bigint,
    annualPriceUSDC: bigint,
    maxDevices: bigint,
    includedContentIds: bigint[],
    isActive: boolean,
    subscriberCount: bigint,
    createdAt: bigint
  ] & {
    planId: bigint;
    creator: string;
    name: string;
    description: string;
    monthlyPriceUSDC: bigint;
    annualPriceUSDC: bigint;
    maxDevices: bigint;
    includedContentIds: bigint[];
    isActive: boolean;
    subscriberCount: bigint;
    createdAt: bigint;
  };

  export type SubscriptionStruct = {
    subscriptionId: BigNumberish;
    subscriber: AddressLike;
    planId: BigNumberish;
    startedAt: BigNumberish;
    currentPeriodStart: BigNumberish;
    currentPeriodEnd: BigNumberish;
    nextBillingDate: BigNumberish;
    isAnnual: boolean;
    autoRenew: boolean;
    isCancelled: boolean;
    registeredDevices: BytesLike[];
    totalPaid: BigNumberish;
  };

  export type SubscriptionStructOutput = [
    subscriptionId: bigint,
    subscriber: string,
    planId: bigint,
    startedAt: bigint,
    currentPeriodStart: bigint,
    currentPeriodEnd: bigint,
    nextBillingDate: bigint,
    isAnnual: boolean,
    autoRenew: boolean,
    isCancelled: boolean,
    registeredDevices: string[],
    totalPaid: bigint
  ] & {
    subscriptionId: bigint;
    subscriber: string;
    planId: bigint;
    startedAt: bigint;
    currentPeriodStart: bigint;
    currentPeriodEnd: bigint;
    nextBillingDate: bigint;
    isAnnual: boolean;
    autoRenew: boolean;
    isCancelled: boolean;
    registeredDevices: string[];
    totalPaid: bigint;
  };
}

export interface PaywallSubscriptionsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "GRACE_PERIOD"
      | "MONTH_DURATION"
      | "YEAR_DURATION"
      | "addContentToPlan"
      | "cancelSubscription"
      | "checkSubscriptionAccess"
      | "createPlan"
      | "creatorBalances"
      | "creatorPlans"
      | "getCreatorPlans"
      | "getPlan"
      | "getRoleAdmin"
      | "getSubscription"
      | "getUserSubscriptions"
      | "grantRole"
      | "hasRole"
      | "isSubscriptionActive"
      | "pause"
      | "paused"
      | "planContentIncluded"
      | "plans"
      | "platformFeeBps"
      | "recordSubscriptionAccess"
      | "registerDevice"
      | "removeContentFromPlan"
      | "renewSubscription"
      | "renounceRole"
      | "revokeRole"
      | "setPlatformFee"
      | "subscribe"
      | "subscriptionAccess"
      | "subscriptions"
      | "supportsInterface"
      | "treasury"
      | "unpause"
      | "updatePlanStatus"
      | "usdcToken"
      | "userSubscriptions"
      | "withdrawCreatorBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorWithdrawal"
      | "DeviceRegistered"
      | "Paused"
      | "PlanCreated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Subscribed"
      | "SubscriptionCancelled"
      | "SubscriptionRenewed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MONTH_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "YEAR_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addContentToPlan",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSubscriptionAccess",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPlan",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorPlans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorPlans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSubscriptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSubscriptionActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "planContentIncluded",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "plans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordSubscriptionAccess",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDevice",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeContentFromPlan",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renewSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionAccess",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updatePlanStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userSubscriptions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCreatorBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MONTH_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "YEAR_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addContentToPlan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSubscriptionAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorPlans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorPlans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSubscriptionActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "planContentIncluded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "plans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSubscriptionAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeContentFromPlan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renewSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePlanStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCreatorBalance",
    data: BytesLike
  ): Result;
}

export namespace CreatorWithdrawalEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceRegisteredEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    deviceFingerprint: BytesLike
  ];
  export type OutputTuple = [subscriptionId: bigint, deviceFingerprint: string];
  export interface OutputObject {
    subscriptionId: bigint;
    deviceFingerprint: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanCreatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    creator: AddressLike,
    name: string,
    monthlyPrice: BigNumberish,
    annualPrice: BigNumberish
  ];
  export type OutputTuple = [
    planId: bigint,
    creator: string,
    name: string,
    monthlyPrice: bigint,
    annualPrice: bigint
  ];
  export interface OutputObject {
    planId: bigint;
    creator: string;
    name: string;
    monthlyPrice: bigint;
    annualPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    subscriber: AddressLike,
    planId: BigNumberish,
    isAnnual: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    subscriber: string,
    planId: bigint,
    isAnnual: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    subscriber: string;
    planId: bigint;
    isAnnual: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    subscriber: AddressLike
  ];
  export type OutputTuple = [subscriptionId: bigint, subscriber: string];
  export interface OutputObject {
    subscriptionId: bigint;
    subscriber: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionRenewedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    amount: BigNumberish,
    newPeriodEnd: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    amount: bigint,
    newPeriodEnd: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    amount: bigint;
    newPeriodEnd: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaywallSubscriptions extends BaseContract {
  connect(runner?: ContractRunner | null): PaywallSubscriptions;
  waitForDeployment(): Promise<this>;

  interface: PaywallSubscriptionsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GRACE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MONTH_DURATION: TypedContractMethod<[], [bigint], "view">;

  YEAR_DURATION: TypedContractMethod<[], [bigint], "view">;

  addContentToPlan: TypedContractMethod<
    [planId: BigNumberish, contentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelSubscription: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkSubscriptionAccess: TypedContractMethod<
    [
      subscriber: AddressLike,
      contentId: BigNumberish,
      deviceFingerprint: BytesLike
    ],
    [[boolean, bigint] & { hasAccess: boolean; subscriptionId: bigint }],
    "view"
  >;

  createPlan: TypedContractMethod<
    [
      name: string,
      description: string,
      monthlyPrice: BigNumberish,
      annualPrice: BigNumberish,
      maxDevices: BigNumberish,
      contentIds: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;

  creatorBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  creatorPlans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getCreatorPlans: TypedContractMethod<
    [creator: AddressLike],
    [bigint[]],
    "view"
  >;

  getPlan: TypedContractMethod<
    [planId: BigNumberish],
    [PaywallSubscriptions.SubscriptionPlanStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSubscription: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [PaywallSubscriptions.SubscriptionStructOutput],
    "view"
  >;

  getUserSubscriptions: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isSubscriptionActive: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  planContentIncluded: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  plans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        planId: bigint;
        creator: string;
        name: string;
        description: string;
        monthlyPriceUSDC: bigint;
        annualPriceUSDC: bigint;
        maxDevices: bigint;
        isActive: boolean;
        subscriberCount: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  recordSubscriptionAccess: TypedContractMethod<
    [subscriptionId: BigNumberish, deviceFingerprint: BytesLike],
    [void],
    "nonpayable"
  >;

  registerDevice: TypedContractMethod<
    [subscriptionId: BigNumberish, deviceFingerprint: BytesLike],
    [void],
    "nonpayable"
  >;

  removeContentFromPlan: TypedContractMethod<
    [planId: BigNumberish, contentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renewSubscription: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<
    [
      planId: BigNumberish,
      isAnnual: boolean,
      initialDeviceFingerprint: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  subscriptionAccess: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint, bigint, boolean] & {
        subscriptionId: bigint;
        deviceFingerprint: string;
        grantedAt: bigint;
        accessCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  subscriptions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        bigint
      ] & {
        subscriptionId: bigint;
        subscriber: string;
        planId: bigint;
        startedAt: bigint;
        currentPeriodStart: bigint;
        currentPeriodEnd: bigint;
        nextBillingDate: bigint;
        isAnnual: boolean;
        autoRenew: boolean;
        isCancelled: boolean;
        totalPaid: bigint;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updatePlanStatus: TypedContractMethod<
    [planId: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  userSubscriptions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawCreatorBalance: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GRACE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MONTH_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "YEAR_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addContentToPlan"
  ): TypedContractMethod<
    [planId: BigNumberish, contentId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelSubscription"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkSubscriptionAccess"
  ): TypedContractMethod<
    [
      subscriber: AddressLike,
      contentId: BigNumberish,
      deviceFingerprint: BytesLike
    ],
    [[boolean, bigint] & { hasAccess: boolean; subscriptionId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "createPlan"
  ): TypedContractMethod<
    [
      name: string,
      description: string,
      monthlyPrice: BigNumberish,
      annualPrice: BigNumberish,
      maxDevices: BigNumberish,
      contentIds: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "creatorPlans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreatorPlans"
  ): TypedContractMethod<[creator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPlan"
  ): TypedContractMethod<
    [planId: BigNumberish],
    [PaywallSubscriptions.SubscriptionPlanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [subscriptionId: BigNumberish],
    [PaywallSubscriptions.SubscriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSubscriptions"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSubscriptionActive"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "planContentIncluded"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "plans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        planId: bigint;
        creator: string;
        name: string;
        description: string;
        monthlyPriceUSDC: bigint;
        annualPriceUSDC: bigint;
        maxDevices: bigint;
        isActive: boolean;
        subscriberCount: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordSubscriptionAccess"
  ): TypedContractMethod<
    [subscriptionId: BigNumberish, deviceFingerprint: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerDevice"
  ): TypedContractMethod<
    [subscriptionId: BigNumberish, deviceFingerprint: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeContentFromPlan"
  ): TypedContractMethod<
    [planId: BigNumberish, contentId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renewSubscription"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<
    [
      planId: BigNumberish,
      isAnnual: boolean,
      initialDeviceFingerprint: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscriptionAccess"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint, bigint, boolean] & {
        subscriptionId: bigint;
        deviceFingerprint: string;
        grantedAt: bigint;
        accessCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        bigint
      ] & {
        subscriptionId: bigint;
        subscriber: string;
        planId: bigint;
        startedAt: bigint;
        currentPeriodStart: bigint;
        currentPeriodEnd: bigint;
        nextBillingDate: bigint;
        isAnnual: boolean;
        autoRenew: boolean;
        isCancelled: boolean;
        totalPaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlanStatus"
  ): TypedContractMethod<
    [planId: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userSubscriptions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawCreatorBalance"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CreatorWithdrawal"
  ): TypedContractEvent<
    CreatorWithdrawalEvent.InputTuple,
    CreatorWithdrawalEvent.OutputTuple,
    CreatorWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "DeviceRegistered"
  ): TypedContractEvent<
    DeviceRegisteredEvent.InputTuple,
    DeviceRegisteredEvent.OutputTuple,
    DeviceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlanCreated"
  ): TypedContractEvent<
    PlanCreatedEvent.InputTuple,
    PlanCreatedEvent.OutputTuple,
    PlanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionRenewed"
  ): TypedContractEvent<
    SubscriptionRenewedEvent.InputTuple,
    SubscriptionRenewedEvent.OutputTuple,
    SubscriptionRenewedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CreatorWithdrawal(address,uint256)": TypedContractEvent<
      CreatorWithdrawalEvent.InputTuple,
      CreatorWithdrawalEvent.OutputTuple,
      CreatorWithdrawalEvent.OutputObject
    >;
    CreatorWithdrawal: TypedContractEvent<
      CreatorWithdrawalEvent.InputTuple,
      CreatorWithdrawalEvent.OutputTuple,
      CreatorWithdrawalEvent.OutputObject
    >;

    "DeviceRegistered(uint256,bytes32)": TypedContractEvent<
      DeviceRegisteredEvent.InputTuple,
      DeviceRegisteredEvent.OutputTuple,
      DeviceRegisteredEvent.OutputObject
    >;
    DeviceRegistered: TypedContractEvent<
      DeviceRegisteredEvent.InputTuple,
      DeviceRegisteredEvent.OutputTuple,
      DeviceRegisteredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlanCreated(uint256,address,string,uint256,uint256)": TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;
    PlanCreated: TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Subscribed(uint256,address,uint256,bool,uint256)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;

    "SubscriptionCancelled(uint256,address)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;

    "SubscriptionRenewed(uint256,uint256,uint256)": TypedContractEvent<
      SubscriptionRenewedEvent.InputTuple,
      SubscriptionRenewedEvent.OutputTuple,
      SubscriptionRenewedEvent.OutputObject
    >;
    SubscriptionRenewed: TypedContractEvent<
      SubscriptionRenewedEvent.InputTuple,
      SubscriptionRenewedEvent.OutputTuple,
      SubscriptionRenewedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
