/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PaywallRegistry {
  export type ContentMetadataStruct = {
    contentId: BigNumberish;
    creator: AddressLike;
    contentType: BigNumberish;
    title: string;
    description: string;
    thumbnailHash: string;
    tags: string[];
    createdAt: BigNumberish;
    lastModified: BigNumberish;
    isFeatured: boolean;
    rating: BigNumberish;
    ratingCount: BigNumberish;
  };

  export type ContentMetadataStructOutput = [
    contentId: bigint,
    creator: string,
    contentType: bigint,
    title: string,
    description: string,
    thumbnailHash: string,
    tags: string[],
    createdAt: bigint,
    lastModified: bigint,
    isFeatured: boolean,
    rating: bigint,
    ratingCount: bigint
  ] & {
    contentId: bigint;
    creator: string;
    contentType: bigint;
    title: string;
    description: string;
    thumbnailHash: string;
    tags: string[];
    createdAt: bigint;
    lastModified: bigint;
    isFeatured: boolean;
    rating: bigint;
    ratingCount: bigint;
  };

  export type CreatorStruct = {
    wallet: AddressLike;
    isVerified: boolean;
    isActive: boolean;
    totalRevenue: BigNumberish;
    totalContent: BigNumberish;
    totalSubscribers: BigNumberish;
    registeredAt: BigNumberish;
    profileHash: string;
    name: string;
    email: string;
    customFeeBps: BigNumberish;
  };

  export type CreatorStructOutput = [
    wallet: string,
    isVerified: boolean,
    isActive: boolean,
    totalRevenue: bigint,
    totalContent: bigint,
    totalSubscribers: bigint,
    registeredAt: bigint,
    profileHash: string,
    name: string,
    email: string,
    customFeeBps: bigint
  ] & {
    wallet: string;
    isVerified: boolean;
    isActive: boolean;
    totalRevenue: bigint;
    totalContent: bigint;
    totalSubscribers: bigint;
    registeredAt: bigint;
    profileHash: string;
    name: string;
    email: string;
    customFeeBps: bigint;
  };
}

export interface PaywallRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "VERIFIER_ROLE"
      | "bannedCreators"
      | "categoryConfigs"
      | "contentMetadata"
      | "creatorContentIds"
      | "creators"
      | "featuredContent"
      | "getContentMetadata"
      | "getCreator"
      | "getCreatorContentIds"
      | "getEffectiveFeeRate"
      | "getPlatformStats"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isCreatorActive"
      | "pause"
      | "paused"
      | "platformConfig"
      | "rateContent"
      | "registerContentMetadata"
      | "registerCreator"
      | "renounceRole"
      | "revokeRole"
      | "setContentFeatured"
      | "setCreatorCustomFee"
      | "setCreatorStatus"
      | "supportsInterface"
      | "totalContent"
      | "totalCreators"
      | "totalRevenue"
      | "totalVerifiedCreators"
      | "unpause"
      | "updateCategoryConfig"
      | "updateContentMetadata"
      | "updateCreatorProfile"
      | "updateCreatorStats"
      | "updatePlatformConfig"
      | "usedProfileHashes"
      | "verifyCreator"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CategoryConfigUpdated"
      | "ContentFeatured"
      | "ContentMetadataUpdated"
      | "ContentRated"
      | "ContentRegistered"
      | "CreatorRegistered"
      | "CreatorStatusChanged"
      | "CreatorVerified"
      | "Paused"
      | "PlatformConfigUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bannedCreators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "categoryConfigs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contentMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorContentIds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "featuredContent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContentMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorContentIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEffectiveFeeRate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCreatorActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rateContent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerContentMetadata",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      string,
      string,
      string,
      string[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCreator",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setContentFeatured",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorCustomFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorStatus",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalContent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCreators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVerifiedCreators",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateCategoryConfig",
    values: [
      BigNumberish,
      BigNumberish,
      boolean,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContentMetadata",
    values: [BigNumberish, string, string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCreatorProfile",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCreatorStats",
    values: [AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformConfig",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      boolean,
      boolean,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "usedProfileHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCreator",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bannedCreators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "categoryConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contentMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorContentIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creators", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "featuredContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContentMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCreator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorContentIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEffectiveFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCreatorActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerContentMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setContentFeatured",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorCustomFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCreators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVerifiedCreators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateCategoryConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContentMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCreatorProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCreatorStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedProfileHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCreator",
    data: BytesLike
  ): Result;
}

export namespace CategoryConfigUpdatedEvent {
  export type InputTuple = [
    category: BigNumberish,
    feeBps: BigNumberish,
    isActive: boolean
  ];
  export type OutputTuple = [
    category: bigint,
    feeBps: bigint,
    isActive: boolean
  ];
  export interface OutputObject {
    category: bigint;
    feeBps: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContentFeaturedEvent {
  export type InputTuple = [contentId: BigNumberish, featured: boolean];
  export type OutputTuple = [contentId: bigint, featured: boolean];
  export interface OutputObject {
    contentId: bigint;
    featured: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContentMetadataUpdatedEvent {
  export type InputTuple = [
    contentId: BigNumberish,
    title: string,
    description: string
  ];
  export type OutputTuple = [
    contentId: bigint,
    title: string,
    description: string
  ];
  export interface OutputObject {
    contentId: bigint;
    title: string;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContentRatedEvent {
  export type InputTuple = [
    contentId: BigNumberish,
    rater: AddressLike,
    rating: BigNumberish,
    newAverage: BigNumberish
  ];
  export type OutputTuple = [
    contentId: bigint,
    rater: string,
    rating: bigint,
    newAverage: bigint
  ];
  export interface OutputObject {
    contentId: bigint;
    rater: string;
    rating: bigint;
    newAverage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContentRegisteredEvent {
  export type InputTuple = [
    contentId: BigNumberish,
    creator: AddressLike,
    contentType: BigNumberish,
    title: string
  ];
  export type OutputTuple = [
    contentId: bigint,
    creator: string,
    contentType: bigint,
    title: string
  ];
  export interface OutputObject {
    contentId: bigint;
    creator: string;
    contentType: bigint;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorRegisteredEvent {
  export type InputTuple = [
    creator: AddressLike,
    name: string,
    profileHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    name: string,
    profileHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    creator: string;
    name: string;
    profileHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorStatusChangedEvent {
  export type InputTuple = [creator: AddressLike, isActive: boolean];
  export type OutputTuple = [creator: string, isActive: boolean];
  export interface OutputObject {
    creator: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorVerifiedEvent {
  export type InputTuple = [creator: AddressLike, verifiedBy: AddressLike];
  export type OutputTuple = [creator: string, verifiedBy: string];
  export interface OutputObject {
    creator: string;
    verifiedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformConfigUpdatedEvent {
  export type InputTuple = [
    defaultFeeBps: BigNumberish,
    treasury: AddressLike,
    paymentsEnabled: boolean
  ];
  export type OutputTuple = [
    defaultFeeBps: bigint,
    treasury: string,
    paymentsEnabled: boolean
  ];
  export interface OutputObject {
    defaultFeeBps: bigint;
    treasury: string;
    paymentsEnabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaywallRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PaywallRegistry;
  waitForDeployment(): Promise<this>;

  interface: PaywallRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  bannedCreators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  categoryConfigs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, string, bigint, bigint] & {
        category: bigint;
        feeBps: bigint;
        isActive: boolean;
        name: string;
        minPrice: bigint;
        maxPrice: bigint;
      }
    ],
    "view"
  >;

  contentMetadata: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        contentId: bigint;
        creator: string;
        contentType: bigint;
        title: string;
        description: string;
        thumbnailHash: string;
        createdAt: bigint;
        lastModified: bigint;
        isFeatured: boolean;
        rating: bigint;
        ratingCount: bigint;
      }
    ],
    "view"
  >;

  creatorContentIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  creators: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        wallet: string;
        isVerified: boolean;
        isActive: boolean;
        totalRevenue: bigint;
        totalContent: bigint;
        totalSubscribers: bigint;
        registeredAt: bigint;
        profileHash: string;
        name: string;
        email: string;
        customFeeBps: bigint;
      }
    ],
    "view"
  >;

  featuredContent: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getContentMetadata: TypedContractMethod<
    [contentId: BigNumberish],
    [PaywallRegistry.ContentMetadataStructOutput],
    "view"
  >;

  getCreator: TypedContractMethod<
    [creator: AddressLike],
    [PaywallRegistry.CreatorStructOutput],
    "view"
  >;

  getCreatorContentIds: TypedContractMethod<
    [creator: AddressLike],
    [bigint[]],
    "view"
  >;

  getEffectiveFeeRate: TypedContractMethod<
    [creator: AddressLike, contentType: BigNumberish],
    [bigint],
    "view"
  >;

  getPlatformStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalCreators: bigint;
        _totalVerifiedCreators: bigint;
        _totalContent: bigint;
        _totalRevenue: bigint;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isCreatorActive: TypedContractMethod<
    [creator: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformConfig: TypedContractMethod<
    [],
    [
      [bigint, bigint, string, string, boolean, boolean, bigint, bigint] & {
        defaultFeeBps: bigint;
        maxFeeBps: bigint;
        treasury: string;
        feeRecipient: string;
        paymentsEnabled: boolean;
        subscriptionsEnabled: boolean;
        minContentPrice: bigint;
        maxContentPrice: bigint;
      }
    ],
    "view"
  >;

  rateContent: TypedContractMethod<
    [contentId: BigNumberish, rating: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerContentMetadata: TypedContractMethod<
    [
      contentId: BigNumberish,
      creator: AddressLike,
      contentType: BigNumberish,
      title: string,
      description: string,
      thumbnailHash: string,
      tags: string[]
    ],
    [void],
    "nonpayable"
  >;

  registerCreator: TypedContractMethod<
    [name: string, email: string, profileHash: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setContentFeatured: TypedContractMethod<
    [contentId: BigNumberish, featured: boolean],
    [void],
    "nonpayable"
  >;

  setCreatorCustomFee: TypedContractMethod<
    [creator: AddressLike, feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCreatorStatus: TypedContractMethod<
    [creator: AddressLike, isActive: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalContent: TypedContractMethod<[], [bigint], "view">;

  totalCreators: TypedContractMethod<[], [bigint], "view">;

  totalRevenue: TypedContractMethod<[], [bigint], "view">;

  totalVerifiedCreators: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateCategoryConfig: TypedContractMethod<
    [
      category: BigNumberish,
      feeBps: BigNumberish,
      isActive: boolean,
      name: string,
      minPrice: BigNumberish,
      maxPrice: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateContentMetadata: TypedContractMethod<
    [
      contentId: BigNumberish,
      title: string,
      description: string,
      thumbnailHash: string,
      tags: string[]
    ],
    [void],
    "nonpayable"
  >;

  updateCreatorProfile: TypedContractMethod<
    [name: string, email: string, newProfileHash: string],
    [void],
    "nonpayable"
  >;

  updateCreatorStats: TypedContractMethod<
    [
      creator: AddressLike,
      revenueIncrease: BigNumberish,
      subscriberChange: BigNumberish,
      isSubscriberIncrease: boolean
    ],
    [void],
    "nonpayable"
  >;

  updatePlatformConfig: TypedContractMethod<
    [
      defaultFeeBps: BigNumberish,
      maxFeeBps: BigNumberish,
      treasury: AddressLike,
      paymentsEnabled: boolean,
      subscriptionsEnabled: boolean,
      minContentPrice: BigNumberish,
      maxContentPrice: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  usedProfileHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyCreator: TypedContractMethod<
    [creator: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bannedCreators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "categoryConfigs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, string, bigint, bigint] & {
        category: bigint;
        feeBps: bigint;
        isActive: boolean;
        name: string;
        minPrice: bigint;
        maxPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "contentMetadata"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        contentId: bigint;
        creator: string;
        contentType: bigint;
        title: string;
        description: string;
        thumbnailHash: string;
        createdAt: bigint;
        lastModified: bigint;
        isFeatured: boolean;
        rating: bigint;
        ratingCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "creatorContentIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "creators"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        wallet: string;
        isVerified: boolean;
        isActive: boolean;
        totalRevenue: bigint;
        totalContent: bigint;
        totalSubscribers: bigint;
        registeredAt: bigint;
        profileHash: string;
        name: string;
        email: string;
        customFeeBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "featuredContent"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getContentMetadata"
  ): TypedContractMethod<
    [contentId: BigNumberish],
    [PaywallRegistry.ContentMetadataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreator"
  ): TypedContractMethod<
    [creator: AddressLike],
    [PaywallRegistry.CreatorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreatorContentIds"
  ): TypedContractMethod<[creator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getEffectiveFeeRate"
  ): TypedContractMethod<
    [creator: AddressLike, contentType: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlatformStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalCreators: bigint;
        _totalVerifiedCreators: bigint;
        _totalContent: bigint;
        _totalRevenue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCreatorActive"
  ): TypedContractMethod<[creator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformConfig"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, string, string, boolean, boolean, bigint, bigint] & {
        defaultFeeBps: bigint;
        maxFeeBps: bigint;
        treasury: string;
        feeRecipient: string;
        paymentsEnabled: boolean;
        subscriptionsEnabled: boolean;
        minContentPrice: bigint;
        maxContentPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rateContent"
  ): TypedContractMethod<
    [contentId: BigNumberish, rating: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerContentMetadata"
  ): TypedContractMethod<
    [
      contentId: BigNumberish,
      creator: AddressLike,
      contentType: BigNumberish,
      title: string,
      description: string,
      thumbnailHash: string,
      tags: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerCreator"
  ): TypedContractMethod<
    [name: string, email: string, profileHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setContentFeatured"
  ): TypedContractMethod<
    [contentId: BigNumberish, featured: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCreatorCustomFee"
  ): TypedContractMethod<
    [creator: AddressLike, feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCreatorStatus"
  ): TypedContractMethod<
    [creator: AddressLike, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalContent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalCreators"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVerifiedCreators"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCategoryConfig"
  ): TypedContractMethod<
    [
      category: BigNumberish,
      feeBps: BigNumberish,
      isActive: boolean,
      name: string,
      minPrice: BigNumberish,
      maxPrice: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateContentMetadata"
  ): TypedContractMethod<
    [
      contentId: BigNumberish,
      title: string,
      description: string,
      thumbnailHash: string,
      tags: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCreatorProfile"
  ): TypedContractMethod<
    [name: string, email: string, newProfileHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCreatorStats"
  ): TypedContractMethod<
    [
      creator: AddressLike,
      revenueIncrease: BigNumberish,
      subscriberChange: BigNumberish,
      isSubscriberIncrease: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePlatformConfig"
  ): TypedContractMethod<
    [
      defaultFeeBps: BigNumberish,
      maxFeeBps: BigNumberish,
      treasury: AddressLike,
      paymentsEnabled: boolean,
      subscriptionsEnabled: boolean,
      minContentPrice: BigNumberish,
      maxContentPrice: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usedProfileHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyCreator"
  ): TypedContractMethod<[creator: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CategoryConfigUpdated"
  ): TypedContractEvent<
    CategoryConfigUpdatedEvent.InputTuple,
    CategoryConfigUpdatedEvent.OutputTuple,
    CategoryConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContentFeatured"
  ): TypedContractEvent<
    ContentFeaturedEvent.InputTuple,
    ContentFeaturedEvent.OutputTuple,
    ContentFeaturedEvent.OutputObject
  >;
  getEvent(
    key: "ContentMetadataUpdated"
  ): TypedContractEvent<
    ContentMetadataUpdatedEvent.InputTuple,
    ContentMetadataUpdatedEvent.OutputTuple,
    ContentMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContentRated"
  ): TypedContractEvent<
    ContentRatedEvent.InputTuple,
    ContentRatedEvent.OutputTuple,
    ContentRatedEvent.OutputObject
  >;
  getEvent(
    key: "ContentRegistered"
  ): TypedContractEvent<
    ContentRegisteredEvent.InputTuple,
    ContentRegisteredEvent.OutputTuple,
    ContentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CreatorRegistered"
  ): TypedContractEvent<
    CreatorRegisteredEvent.InputTuple,
    CreatorRegisteredEvent.OutputTuple,
    CreatorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CreatorStatusChanged"
  ): TypedContractEvent<
    CreatorStatusChangedEvent.InputTuple,
    CreatorStatusChangedEvent.OutputTuple,
    CreatorStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorVerified"
  ): TypedContractEvent<
    CreatorVerifiedEvent.InputTuple,
    CreatorVerifiedEvent.OutputTuple,
    CreatorVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformConfigUpdated"
  ): TypedContractEvent<
    PlatformConfigUpdatedEvent.InputTuple,
    PlatformConfigUpdatedEvent.OutputTuple,
    PlatformConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CategoryConfigUpdated(uint8,uint256,bool)": TypedContractEvent<
      CategoryConfigUpdatedEvent.InputTuple,
      CategoryConfigUpdatedEvent.OutputTuple,
      CategoryConfigUpdatedEvent.OutputObject
    >;
    CategoryConfigUpdated: TypedContractEvent<
      CategoryConfigUpdatedEvent.InputTuple,
      CategoryConfigUpdatedEvent.OutputTuple,
      CategoryConfigUpdatedEvent.OutputObject
    >;

    "ContentFeatured(uint256,bool)": TypedContractEvent<
      ContentFeaturedEvent.InputTuple,
      ContentFeaturedEvent.OutputTuple,
      ContentFeaturedEvent.OutputObject
    >;
    ContentFeatured: TypedContractEvent<
      ContentFeaturedEvent.InputTuple,
      ContentFeaturedEvent.OutputTuple,
      ContentFeaturedEvent.OutputObject
    >;

    "ContentMetadataUpdated(uint256,string,string)": TypedContractEvent<
      ContentMetadataUpdatedEvent.InputTuple,
      ContentMetadataUpdatedEvent.OutputTuple,
      ContentMetadataUpdatedEvent.OutputObject
    >;
    ContentMetadataUpdated: TypedContractEvent<
      ContentMetadataUpdatedEvent.InputTuple,
      ContentMetadataUpdatedEvent.OutputTuple,
      ContentMetadataUpdatedEvent.OutputObject
    >;

    "ContentRated(uint256,address,uint256,uint256)": TypedContractEvent<
      ContentRatedEvent.InputTuple,
      ContentRatedEvent.OutputTuple,
      ContentRatedEvent.OutputObject
    >;
    ContentRated: TypedContractEvent<
      ContentRatedEvent.InputTuple,
      ContentRatedEvent.OutputTuple,
      ContentRatedEvent.OutputObject
    >;

    "ContentRegistered(uint256,address,uint8,string)": TypedContractEvent<
      ContentRegisteredEvent.InputTuple,
      ContentRegisteredEvent.OutputTuple,
      ContentRegisteredEvent.OutputObject
    >;
    ContentRegistered: TypedContractEvent<
      ContentRegisteredEvent.InputTuple,
      ContentRegisteredEvent.OutputTuple,
      ContentRegisteredEvent.OutputObject
    >;

    "CreatorRegistered(address,string,string,uint256)": TypedContractEvent<
      CreatorRegisteredEvent.InputTuple,
      CreatorRegisteredEvent.OutputTuple,
      CreatorRegisteredEvent.OutputObject
    >;
    CreatorRegistered: TypedContractEvent<
      CreatorRegisteredEvent.InputTuple,
      CreatorRegisteredEvent.OutputTuple,
      CreatorRegisteredEvent.OutputObject
    >;

    "CreatorStatusChanged(address,bool)": TypedContractEvent<
      CreatorStatusChangedEvent.InputTuple,
      CreatorStatusChangedEvent.OutputTuple,
      CreatorStatusChangedEvent.OutputObject
    >;
    CreatorStatusChanged: TypedContractEvent<
      CreatorStatusChangedEvent.InputTuple,
      CreatorStatusChangedEvent.OutputTuple,
      CreatorStatusChangedEvent.OutputObject
    >;

    "CreatorVerified(address,address)": TypedContractEvent<
      CreatorVerifiedEvent.InputTuple,
      CreatorVerifiedEvent.OutputTuple,
      CreatorVerifiedEvent.OutputObject
    >;
    CreatorVerified: TypedContractEvent<
      CreatorVerifiedEvent.InputTuple,
      CreatorVerifiedEvent.OutputTuple,
      CreatorVerifiedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformConfigUpdated(uint256,address,bool)": TypedContractEvent<
      PlatformConfigUpdatedEvent.InputTuple,
      PlatformConfigUpdatedEvent.OutputTuple,
      PlatformConfigUpdatedEvent.OutputObject
    >;
    PlatformConfigUpdated: TypedContractEvent<
      PlatformConfigUpdatedEvent.InputTuple,
      PlatformConfigUpdatedEvent.OutputTuple,
      PlatformConfigUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
