/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PaywallCore {
  export type ContentStruct = {
    contentId: BigNumberish;
    creator: AddressLike;
    priceUSDC: BigNumberish;
    accessDuration: BigNumberish;
    maxDevices: BigNumberish;
    isActive: boolean;
    totalRevenue: BigNumberish;
    accessCount: BigNumberish;
    contentHash: string;
    createdAt: BigNumberish;
  };

  export type ContentStructOutput = [
    contentId: bigint,
    creator: string,
    priceUSDC: bigint,
    accessDuration: bigint,
    maxDevices: bigint,
    isActive: boolean,
    totalRevenue: bigint,
    accessCount: bigint,
    contentHash: string,
    createdAt: bigint
  ] & {
    contentId: bigint;
    creator: string;
    priceUSDC: bigint;
    accessDuration: bigint;
    maxDevices: bigint;
    isActive: boolean;
    totalRevenue: bigint;
    accessCount: bigint;
    contentHash: string;
    createdAt: bigint;
  };

  export type PaymentStruct = {
    paymentHash: BytesLike;
    payer: AddressLike;
    contentId: BigNumberish;
    amount: BigNumberish;
    timestamp: BigNumberish;
    expiresAt: BigNumberish;
    completed: boolean;
    refunded: boolean;
    deviceFingerprints: BytesLike[];
  };

  export type PaymentStructOutput = [
    paymentHash: string,
    payer: string,
    contentId: bigint,
    amount: bigint,
    timestamp: bigint,
    expiresAt: bigint,
    completed: boolean,
    refunded: boolean,
    deviceFingerprints: string[]
  ] & {
    paymentHash: string;
    payer: string;
    contentId: bigint;
    amount: bigint;
    timestamp: bigint;
    expiresAt: bigint;
    completed: boolean;
    refunded: boolean;
    deviceFingerprints: string[];
  };
}

export interface PaywallCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_FEE_BPS"
      | "ORACLE_ROLE"
      | "completePayment"
      | "contentDeviceCount"
      | "contentDeviceUsed"
      | "contents"
      | "createPayment"
      | "creatorBalances"
      | "creatorContent"
      | "deviceAccess"
      | "getContent"
      | "getCreatorContent"
      | "getPayment"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "pause"
      | "paused"
      | "payments"
      | "platformFeeBps"
      | "recordAccess"
      | "refundExpiredPayment"
      | "registerContent"
      | "renounceRole"
      | "revokeDeviceAccess"
      | "revokeRole"
      | "setContentStatus"
      | "setPlatformFee"
      | "supportsInterface"
      | "treasury"
      | "unpause"
      | "updateContentPrice"
      | "updateTreasury"
      | "usdcToken"
      | "verifyAccess"
      | "withdrawCreatorBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "ContentRegistered"
      | "ContentStatusChanged"
      | "CreatorWithdrawal"
      | "DeviceRevoked"
      | "Paused"
      | "PaymentCompleted"
      | "PaymentCreated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completePayment",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contentDeviceCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contentDeviceUsed",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPayment",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorContent",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deviceAccess",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorContent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "payments", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordAccess",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundExpiredPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerContent",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDeviceAccess",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setContentStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateContentPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyAccess",
    values: [BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCreatorBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contentDeviceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contentDeviceUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getContent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundExpiredPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDeviceAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setContentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateContentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCreatorBalance",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    contentId: BigNumberish,
    deviceFingerprint: BytesLike,
    payer: AddressLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    contentId: bigint,
    deviceFingerprint: string,
    payer: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    contentId: bigint;
    deviceFingerprint: string;
    payer: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContentRegisteredEvent {
  export type InputTuple = [
    contentId: BigNumberish,
    creator: AddressLike,
    price: BigNumberish,
    contentHash: string
  ];
  export type OutputTuple = [
    contentId: bigint,
    creator: string,
    price: bigint,
    contentHash: string
  ];
  export interface OutputObject {
    contentId: bigint;
    creator: string;
    price: bigint;
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContentStatusChangedEvent {
  export type InputTuple = [contentId: BigNumberish, isActive: boolean];
  export type OutputTuple = [contentId: bigint, isActive: boolean];
  export interface OutputObject {
    contentId: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorWithdrawalEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceRevokedEvent {
  export type InputTuple = [
    contentId: BigNumberish,
    deviceFingerprint: BytesLike,
    revokedBy: AddressLike
  ];
  export type OutputTuple = [
    contentId: bigint,
    deviceFingerprint: string,
    revokedBy: string
  ];
  export interface OutputObject {
    contentId: bigint;
    deviceFingerprint: string;
    revokedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCompletedEvent {
  export type InputTuple = [
    paymentHash: BytesLike,
    deviceFingerprint: BytesLike,
    creatorAmount: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    paymentHash: string,
    deviceFingerprint: string,
    creatorAmount: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    paymentHash: string;
    deviceFingerprint: string;
    creatorAmount: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCreatedEvent {
  export type InputTuple = [
    paymentHash: BytesLike,
    payer: AddressLike,
    contentId: BigNumberish,
    amount: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    paymentHash: string,
    payer: string,
    contentId: bigint,
    amount: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    paymentHash: string;
    payer: string;
    contentId: bigint;
    amount: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaywallCore extends BaseContract {
  connect(runner?: ContractRunner | null): PaywallCore;
  waitForDeployment(): Promise<this>;

  interface: PaywallCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  completePayment: TypedContractMethod<
    [preimage: BytesLike, deviceFingerprint: BytesLike],
    [boolean],
    "nonpayable"
  >;

  contentDeviceCount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  contentDeviceUsed: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;

  contents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        contentId: bigint;
        creator: string;
        priceUSDC: bigint;
        accessDuration: bigint;
        maxDevices: bigint;
        isActive: boolean;
        totalRevenue: bigint;
        accessCount: bigint;
        contentHash: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  createPayment: TypedContractMethod<
    [
      paymentHash: BytesLike,
      contentId: BigNumberish,
      expiryMinutes: BigNumberish
    ],
    [string],
    "payable"
  >;

  creatorBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  creatorContent: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  deviceAccess: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        deviceFingerprint: string;
        payer: string;
        contentId: bigint;
        grantedAt: bigint;
        expiresAt: bigint;
        accessCount: bigint;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  getContent: TypedContractMethod<
    [contentId: BigNumberish],
    [PaywallCore.ContentStructOutput],
    "view"
  >;

  getCreatorContent: TypedContractMethod<
    [creator: AddressLike],
    [bigint[]],
    "view"
  >;

  getPayment: TypedContractMethod<
    [paymentId: BytesLike],
    [PaywallCore.PaymentStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        paymentHash: string;
        payer: string;
        contentId: bigint;
        amount: bigint;
        timestamp: bigint;
        expiresAt: bigint;
        completed: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  recordAccess: TypedContractMethod<
    [contentId: BigNumberish, deviceFingerprint: BytesLike],
    [void],
    "nonpayable"
  >;

  refundExpiredPayment: TypedContractMethod<
    [paymentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerContent: TypedContractMethod<
    [
      priceUSDC: BigNumberish,
      accessDuration: BigNumberish,
      maxDevices: BigNumberish,
      contentHash: string
    ],
    [bigint],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeDeviceAccess: TypedContractMethod<
    [contentId: BigNumberish, deviceFingerprint: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setContentStatus: TypedContractMethod<
    [contentId: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateContentPrice: TypedContractMethod<
    [contentId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  verifyAccess: TypedContractMethod<
    [contentId: BigNumberish, deviceFingerprint: BytesLike, user: AddressLike],
    [[boolean, bigint] & { hasAccess: boolean; expiresAt: bigint }],
    "view"
  >;

  withdrawCreatorBalance: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "completePayment"
  ): TypedContractMethod<
    [preimage: BytesLike, deviceFingerprint: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contentDeviceCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "contentDeviceUsed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "contents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        contentId: bigint;
        creator: string;
        priceUSDC: bigint;
        accessDuration: bigint;
        maxDevices: bigint;
        isActive: boolean;
        totalRevenue: bigint;
        accessCount: bigint;
        contentHash: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createPayment"
  ): TypedContractMethod<
    [
      paymentHash: BytesLike,
      contentId: BigNumberish,
      expiryMinutes: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "creatorBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "creatorContent"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deviceAccess"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        deviceFingerprint: string;
        payer: string;
        contentId: bigint;
        grantedAt: bigint;
        expiresAt: bigint;
        accessCount: bigint;
        isRevoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContent"
  ): TypedContractMethod<
    [contentId: BigNumberish],
    [PaywallCore.ContentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreatorContent"
  ): TypedContractMethod<[creator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [PaywallCore.PaymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        paymentHash: string;
        payer: string;
        contentId: bigint;
        amount: bigint;
        timestamp: bigint;
        expiresAt: bigint;
        completed: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordAccess"
  ): TypedContractMethod<
    [contentId: BigNumberish, deviceFingerprint: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refundExpiredPayment"
  ): TypedContractMethod<[paymentHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerContent"
  ): TypedContractMethod<
    [
      priceUSDC: BigNumberish,
      accessDuration: BigNumberish,
      maxDevices: BigNumberish,
      contentHash: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeDeviceAccess"
  ): TypedContractMethod<
    [contentId: BigNumberish, deviceFingerprint: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setContentStatus"
  ): TypedContractMethod<
    [contentId: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateContentPrice"
  ): TypedContractMethod<
    [contentId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyAccess"
  ): TypedContractMethod<
    [contentId: BigNumberish, deviceFingerprint: BytesLike, user: AddressLike],
    [[boolean, bigint] & { hasAccess: boolean; expiresAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawCreatorBalance"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ContentRegistered"
  ): TypedContractEvent<
    ContentRegisteredEvent.InputTuple,
    ContentRegisteredEvent.OutputTuple,
    ContentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ContentStatusChanged"
  ): TypedContractEvent<
    ContentStatusChangedEvent.InputTuple,
    ContentStatusChangedEvent.OutputTuple,
    ContentStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorWithdrawal"
  ): TypedContractEvent<
    CreatorWithdrawalEvent.InputTuple,
    CreatorWithdrawalEvent.OutputTuple,
    CreatorWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "DeviceRevoked"
  ): TypedContractEvent<
    DeviceRevokedEvent.InputTuple,
    DeviceRevokedEvent.OutputTuple,
    DeviceRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCompleted"
  ): TypedContractEvent<
    PaymentCompletedEvent.InputTuple,
    PaymentCompletedEvent.OutputTuple,
    PaymentCompletedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCreated"
  ): TypedContractEvent<
    PaymentCreatedEvent.InputTuple,
    PaymentCreatedEvent.OutputTuple,
    PaymentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(uint256,bytes32,address,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "ContentRegistered(uint256,address,uint256,string)": TypedContractEvent<
      ContentRegisteredEvent.InputTuple,
      ContentRegisteredEvent.OutputTuple,
      ContentRegisteredEvent.OutputObject
    >;
    ContentRegistered: TypedContractEvent<
      ContentRegisteredEvent.InputTuple,
      ContentRegisteredEvent.OutputTuple,
      ContentRegisteredEvent.OutputObject
    >;

    "ContentStatusChanged(uint256,bool)": TypedContractEvent<
      ContentStatusChangedEvent.InputTuple,
      ContentStatusChangedEvent.OutputTuple,
      ContentStatusChangedEvent.OutputObject
    >;
    ContentStatusChanged: TypedContractEvent<
      ContentStatusChangedEvent.InputTuple,
      ContentStatusChangedEvent.OutputTuple,
      ContentStatusChangedEvent.OutputObject
    >;

    "CreatorWithdrawal(address,uint256)": TypedContractEvent<
      CreatorWithdrawalEvent.InputTuple,
      CreatorWithdrawalEvent.OutputTuple,
      CreatorWithdrawalEvent.OutputObject
    >;
    CreatorWithdrawal: TypedContractEvent<
      CreatorWithdrawalEvent.InputTuple,
      CreatorWithdrawalEvent.OutputTuple,
      CreatorWithdrawalEvent.OutputObject
    >;

    "DeviceRevoked(uint256,bytes32,address)": TypedContractEvent<
      DeviceRevokedEvent.InputTuple,
      DeviceRevokedEvent.OutputTuple,
      DeviceRevokedEvent.OutputObject
    >;
    DeviceRevoked: TypedContractEvent<
      DeviceRevokedEvent.InputTuple,
      DeviceRevokedEvent.OutputTuple,
      DeviceRevokedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentCompleted(bytes32,bytes32,uint256,uint256)": TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;
    PaymentCompleted: TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;

    "PaymentCreated(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      PaymentCreatedEvent.InputTuple,
      PaymentCreatedEvent.OutputTuple,
      PaymentCreatedEvent.OutputObject
    >;
    PaymentCreated: TypedContractEvent<
      PaymentCreatedEvent.InputTuple,
      PaymentCreatedEvent.OutputTuple,
      PaymentCreatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
